version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - TELEGRAM_TOKEN=your_telegram_token
      - PAYMENT_PROVIDER_TOKEN=your_payment_token
    volumes:
      - ./bot_database.db:/app/bot_database.db
    restart: unless-stopped

  video_processor:
    build:
      context: .
      dockerfile: Dockerfile.new
    environment:
      - DISPLAY=:99
    volumes:
      - ./:/app
    restart: unless-stopped
    depends_on:
      - bot